### ISSUE TITLE
Kanban Board Setup 

### ISSUE THREAD

**Issue by ishpaul777** [ishpaul777/pokemon-cards-collection#21]
In this activity -
- We set up the Kanban board in the GitHub project - https://github.com/ishpaul777/pokemon-cards-collection/projects/1.
- We are a team of two people @ishpaul777 - student A and @amejid - student B

**Comment by Ghiftee** [comment]
## STATUS: APPROVED ♻️♻️
Hi @ishpaul777 and @amejid, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![](https://media.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif)

Cheers and Happy coding!👏👏👏
